### ISSUE TITLE
Error en go = split_GO

### ISSUE THREAD

**Issue by berumeng** [RJEGR/Transcriptomics#7]
Hola, estoy usando el script anotation.R el cual funciona muy bien. Sin embargo en la parte:

go <- split_GO(x)

obtengo el siguiente error:

Error in .checkTypos(e, names_x) :
Object 'gene_ontology_BLAST' not found. Perhaps you intended gene_ontology_BLASTX, gene_ontology_BLASTP

Por lo que realicé una función de split_GO de la siguiente forma:
split_GO <- function(x, hit = "gene_ontology_BLASTX"){

La cual es prácticamente igual a la split_blast.
Sin embargo le toma mucho tiempo a R y consume mucha memoria RAM (lo corrí local) por lo que detengo el proceso.

Me interesa graficar los términos GO. ¿alguna sugerencia para solucionarlo?
Gracias!

**Comment by RJEGR** [comment]
Que tal @berumeng ,
lograste solucionarlo?
es necesario especificar el tipo de ontologia: gene_ontology_BLASTP o gene_ontology_BLASTX, si son muchos los terminos ontologicos, lo mas probable es que se sature la memoria RAM.

En futuras análisis te recomiendo usar el archivo `Trinotate_report.xls.gene_ontology` que tiene relación de transcritos ensamblados y su anotación GO en un formato mas compatible: Ej.

```
go_file <- paste0(path, 'Trinotate_report.xls.gene_ontology')


MAP <- readMappings(go_file)

head(MAP)

$STRG.1.9
 [1] "GO:0003779" "GO:0005769" "GO:0005770" "GO:0005776" "GO:0005814" "GO:0005829" "GO:0015031"
 [8] "GO:0016197" ...

$STRG.100.1
[1] "GO:0016021" ...

$STRG.1000.1
 [1] "GO:0000932" "GO:0002151" "GO:0003676" "GO:0003723" "GO:0005634" "GO:0005730" "GO:0005737"
 [8] "GO:0005791" "GO:0005829" ...


--

readMappings <-  function (file, sep = "\t", IDsep = ",")  {


# From topGO::readMappings

    a <- read.delim(file = file, header = FALSE, quote = "", 
        sep = sep, colClasses = "character")
    map <- a[, 2]
    names(map) <- gsub(" ", "", a[, 1])
    return(lapply(map, function(x) gsub(" ", "", strsplit(x, 
        split = IDsep)[[1]])))
}


```
